services:
  api:
    image: ghcr.io/zinebmouman/music-api:latest
    environment:
      - UI_ORIGIN=http://localhost:8501
    ports:
      - "8000:8000"

  ui:
    build:
      context: ghcr.io/zinebmouman/music-ui:latest            # <<< IMPORTANT
      dockerfile: Dockerfile.ui  # dans ./ui
    environment:
      - API_URL=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api
