services:
  api:
    image: ghcr.io/${OWNER:-zinebmouman}/music-api:latest
    container_name: music-api
    environment:
      - UI_ORIGIN=http://localhost:8501
    ports:
      - "8000:8000"

  ui:
    image: ghcr.io/${OWNER:-zinebmouman}/music-ui:latest
    container_name: music-ui
    environment:
      - API_URL=http://api:8000
    ports:
      - "8501:8501"
    depends_on:
      - api
