FROM python:3.11-slim
WORKDIR /app

# copier d'abord les deps (meilleur cache)
COPY ui/requirements-ui.txt /app/requirements-ui.txt
RUN pip install --no-cache-dir -r /app/requirements-ui.txt

# puis le code
COPY ui/app.py /app/app.py

ENV API_URL=http://api:8000
EXPOSE 8501
CMD ["streamlit","run","/app/app.py","--server.address","0.0.0.0","--server.port","8501"]
